name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
        include-prerelease: True
    - name: Restore dependencies
      run: dotnet restore ./content/BlazorBffAzureAD/Server
    - name: Build Blazor projects
      run: dotnet build ./content/BlazorBffAzureAD/Server/BlazorBffAzureAD.Server.csproj --no-restore
